name: masters_flying
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  responsive_sizer: ^3.3.1
  hive: ^2.2.3
  go_router: ^14.8.1
  audioplayers: ^6.4.0
  another_flutter_splash_screen: ^1.2.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  flame: ^1.26.0
  flutter_bloc: ^9.1.0
  flame_audio: ^2.11.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/audio/
